language: julia
sudo: false

os:
  - osx

julia:
  - 0.4

notifications:
  email: false

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
      ${AMDAPPSDK}/bin/x86_64/clinfo;
    fi;
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'using OpenCL; @assert isdefined(:OpenCL); @assert typeof(OpenCL) === Module'

  - julia --color=yes --depwarn=error -e "Pkg.test(\"OpenCL\")"
  - julia --color=yes -e "using OpenCL; device, context, queue = OpenCL.create_compute_context(); a = rand(Float32, 125356789); abuf = OpenCL.Buffer(Float32, context, (:r, :copy), hostbuf=a); b = OpenCL.read(queue, abuf); @assert isapprox(a, b)"

after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
