language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq fglrx opencl-headers
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.add("FactCheck");'
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/OpenCL`); Pkg.resolve()'
  - julia -e 'using OpenCL; @assert isdefined(:OpenCL); @assert typeof(OpenCL) === Module'

  - julia --code-coverage test/runtests.jl

  - julia examples/demo.jl
  - julia examples/performance.jl
  - julia examples/hands_on_opencl/ex04/vadd_chain.jl
  - julia examples/hands_on_opencl/ex05/vadd_abc.jl
  - julia examples/hands_on_opencl/ex06/matmul.jl
  - julia examples/hands_on_opencl/ex07/matmul.jl
  - julia examples/hands_on_opencl/ex08/matmul.jl
  - julia examples/hands_on_opencl/ex09/pi_ocl.jl
  - julia examples/hands_on_opencl/exA/pi_vocl.jl 1  
  - julia examples/hands_on_opencl/exA/pi_vocl.jl 4  
  - julia examples/hands_on_opencl/exA/pi_vocl.jl 8 
after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'


